# -*- coding: utf-8 -*-
from gen import Fig

def fig1():
    f = Fig(['Cliente / Admin', 'Plataforma (web)', 'Serviços externos'], 8)
    f.dot('s', 0, 0)
    f.node('cad', 0, 1, 'Cadastrar marca: nome, domínio e aliases', sub='wizard de marca')
    f.node('read', 1, 2, 'Ler o site real da marca', 'sys', sub='preserva o path (/br)')
    f.node('scr', 2, 2, 'Proxy de leitura', 'ext', sub='Scrape.do')
    f.node('sug', 1, 3, 'Sugerir descrição, tópicos, prompts e concorrentes', 'sys', sub='modelo por função · ADR-7')
    f.node('llm', 2, 3, 'Modelo de sugestão', 'ext', sub='provider/modelo via env')
    f.node('rev', 0, 4, 'Revisar e confirmar: nada entra sem aprovação')
    f.node('eng', 0, 5, 'Escolher motores conforme o pacote', sub='4 · 6 · 9 motores')
    f.node('act', 1, 6, 'Ativar prompt-set + prompts de marca', 'sys', sub='is_brand_prompt')
    f.dot('e', 1, 7, end=True)
    f.edge('s', 'cad')
    f.edge('cad', 'read', 'domínio')
    f.edge('read', 'scr', 'URL')
    f.edge('read', 'sug', 'conteúdo lido')
    f.edge('sug', 'llm', 'prompt')
    f.edge('llm', 'rev', 'sugestões')
    f.edge('rev', 'eng')
    f.edge('eng', 'act', 'seleção')
    f.edge('act', 'e')
    return f.svg('Onboarding: cliente cadastra a marca, a plataforma lê o site real via proxy e sugere tópicos, prompts e concorrentes por LLM; o cliente revisa, escolhe os motores do pacote e o prompt-set é ativado.')

def fig2():
    f = Fig(['Agendador', 'Worker de rastreamento', 'Motores de IA', 'Parser & análise', 'Banco'], 9)
    f.dot('s', 0, 0)
    f.node('cron', 0, 1, 'Disparar censo semanal', sub='DAILY_CRON_SCHEDULE')
    f.node('job', 1, 1, 'Criar job e reservar cota', 'sys', sub='tabela jobs · ADR-6')
    f.node('sub', 1, 2, 'Submeter tarefas dos 6 motores web', 'sys', sub='modo webhook · ADR-2')
    f.node('clo', 2, 2, 'Coletor de respostas', 'ext', sub='Cloro · cloro_pending_tasks')
    f.node('drain', 1, 3, 'Drenar fila com 2 orçamentos e stall de 25 min', 'sys', sub='checkpoints de cancelamento')
    f.node('api', 2, 4, 'Modelos de API', 'ext', sub='claude · gemini · chatgpt')
    f.node('parse', 3, 4, 'Contar menções, citações próprias e concorrentes', 'sys', sub='URLs removidas · nome+aliases')
    f.node('dec', 3, 5, 'A marca foi mencionada?', 'dec')
    f.node('sent', 3, 6, 'Analisar sentimento da resposta', 'sys', sub='só quando há menção')
    f.node('row', 4, 7, 'Gravar resultado da resposta', 'sys', sub='prompt_results')
    f.dot('e', 4, 8, end=True)
    f.edge('s', 'cron')
    f.edge('cron', 'job', 'semanal 06:00 UTC')
    f.edge('job', 'sub')
    f.edge('sub', 'clo', 'tarefas')
    f.edge('clo', 'drain', 'callback')
    f.edge('drain', 'api', 'fase 2')
    f.edge('api', 'parse', 'texto + fontes')
    f.edge('parse', 'dec')
    f.edge('dec', 'sent', 'sim')
    f.edge('dec', 'row', 'não · pula o LLM')
    f.edge('sent', 'row', 'positivo/neutro/negativo')
    f.edge('row', 'e')
    return f.svg('Censo semanal: o cron cria o job, o worker submete tarefas aos motores web em modo webhook, drena a fila, roda os modelos de API, o parser conta menções e citações, o sentimento só roda quando há menção e o resultado é gravado.')

def fig3():
    f = Fig(['Crons do server', 'Coleta / enriquecimento', 'Vigias', 'Operador'], 7)
    f.node('c1', 0, 0, 'A cada 30 min', sub='APPEARANCE_RANK_CRON')
    f.node('r1', 1, 0, 'Calcular a ordem de aparição no texto salvo', 'sys', sub='lotes de 200 · sem custo externo')
    f.node('c2', 0, 1, 'Semanal, segunda 08:30', sub='REVIEW_CHECK_CRON')
    f.node('r2', 1, 1, 'Checar plataformas de avaliação', 'sys', sub='Trustpilot · G2 · Capterra')
    f.node('c3', 0, 2, 'Mensal, dia 1', sub='SITE_CRAWL_CRON')
    f.node('r3', 1, 2, 'Varrer até 10 páginas-chave do site', 'sys', sub='sitemap → sinais por página')
    f.node('c4', 0, 4, 'A cada 15 min', sub='WATCHDOG_INTERVAL_MIN')
    f.node('w1', 2, 3, 'Saúde: jobs, fila, sentimento, censo, drift', 'sys', sub='6 checks')
    f.node('w2', 2, 4, 'Consistência: contas, nomes, duplicatas, motor calado', 'sys', sub='10 invariantes')
    f.node('dec', 2, 5, 'Algo fora do esperado?', 'dec')
    f.node('al', 3, 5, 'Alertar por e-mail e webhook', sub='anti-spam de 6 h')
    f.node('ops', 3, 6, 'Painel /ops: saúde, custos e pesos', sub='Basic Auth própria')
    f.edge('c1', 'r1')
    f.edge('c2', 'r2')
    f.edge('c3', 'r3')
    f.edge('c4', 'w1')
    f.edge('w1', 'w2')
    f.edge('w2', 'dec')
    f.edge('dec', 'al', 'sim')
    f.edge('dec', 'ops', 'não · segue no painel')
    f.edge('al', 'ops')
    return f.svg('Enriquecimento e vigilância: crons calculam ranking a cada 30 minutos, checam avaliações semanalmente e varrem o site mensalmente; a cada 15 minutos os vigias avaliam saúde e consistência e, havendo desvio, alertam por e-mail e webhook, com tudo visível no painel do operador.')

def fig4():
    f = Fig(['Banco', 'Índices (app)', 'Telas', 'Cliente'], 6)
    f.node('db', 0, 1, 'Respostas, avaliações, leituras do site', 'sys', sub='mesma fonte para todas as telas')
    f.node('ic', 1, 0, 'Índice de Citabilidade: 6 alavancas', 'sys', sub='pesos calibráveis no /ops')
    f.node('sc', 1, 2, 'Score de Visibilidade: 4 dimensões medidas', 'sys', sub='Leitura · Presença · Ranking · Sentimento')
    f.node('ins', 2, 1, 'Resumo: presença, ranking médio e sentimento', sub='sem nota ponderada')
    f.node('aud', 2, 3, 'Auditoria: o que fazer, lido do site', sub='indicação por evidência')
    f.node('do', 3, 4, 'Executar a correção no site e no conteúdo')
    f.node('next', 0, 5, 'Próximo censo mede o efeito', 'sys', sub='o loop fecha aqui')
    f.edge('db', 'ic', 'ativos lidos')
    f.edge('db', 'sc', 'respostas')
    f.edge('ic', 'sc', 'dirige (semanas depois)')
    f.edge('sc', 'ins', 'resume')
    f.edge('ic', 'aud', 'você controla')
    f.edge('aud', 'do', 'indicação')
    f.edge('do', 'next', 'site alterado')
    return f.svg('Ciclo de valor: o banco alimenta o Índice de Citabilidade e o Score de Visibilidade; o Score é resumido no Insights, a Citabilidade gera as indicações da Auditoria, o cliente executa e o próximo censo mede o efeito.')
